package discordgamesdk;

import com.sun.jna.Callback;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import com.sun.jna.ptr.LongByReference;

import java.util.Arrays;
import java.util.List;

/**
 * <i>native declaration : line 455</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class IDiscordNetworkManager extends Structure {
	/**
	 * Get the local peer ID for this process.<br>
	 * C type : get_peer_id_callback*
	 */
	public get_peer_id_callback get_peer_id;
	/**
	 * Send pending network messages.<br>
	 * C type : flush_callback*
	 */
	public flush_callback flush;
	/**
	 * Open a connection to a remote peer.<br>
	 * C type : open_peer_callback*
	 */
	public open_peer_callback open_peer;
	/**
	 * Update the route data for a connected peer.<br>
	 * C type : update_peer_callback*
	 */
	public update_peer_callback update_peer;
	/**
	 * Close the connection to a remote peer.<br>
	 * C type : close_peer_callback*
	 */
	public close_peer_callback close_peer;
	/**
	 * Open a message channel to a connected peer.<br>
	 * C type : open_channel_callback*
	 */
	public open_channel_callback open_channel;
	/**
	 * Close a message channel to a connected peer.<br>
	 * C type : close_channel_callback*
	 */
	public close_channel_callback close_channel;
	/**
	 * Send a message to a connected peer over an opened message channel.<br>
	 * C type : send_message_callback*
	 */
	public send_message_callback send_message;
	public interface get_peer_id_callback extends Callback {
		void apply(IDiscordNetworkManager manager, LongByReference peer_id);
	};
	public interface flush_callback extends Callback {
		int apply(IDiscordNetworkManager manager);
	};
	public interface open_peer_callback extends Callback {
		int apply(IDiscordNetworkManager manager, long peer_id, Pointer route_data);
	};
	public interface update_peer_callback extends Callback {
		int apply(IDiscordNetworkManager manager, long peer_id, Pointer route_data);
	};
	public interface close_peer_callback extends Callback {
		int apply(IDiscordNetworkManager manager, long peer_id);
	};
	public interface open_channel_callback extends Callback {
		int apply(IDiscordNetworkManager manager, long peer_id, byte channel_id, byte reliable);
	};
	public interface close_channel_callback extends Callback {
		int apply(IDiscordNetworkManager manager, long peer_id, byte channel_id);
	};
	public interface send_message_callback extends Callback {
		int apply(IDiscordNetworkManager manager, long peer_id, byte channel_id, Pointer data, int data_length);
	};
	public IDiscordNetworkManager() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("get_peer_id", "flush", "open_peer", "update_peer", "close_peer", "open_channel", "close_channel", "send_message");
	}
	/**
	 * @param get_peer_id Get the local peer ID for this process.<br>
	 * C type : get_peer_id_callback*<br>
	 * @param flush Send pending network messages.<br>
	 * C type : flush_callback*<br>
	 * @param open_peer Open a connection to a remote peer.<br>
	 * C type : open_peer_callback*<br>
	 * @param update_peer Update the route data for a connected peer.<br>
	 * C type : update_peer_callback*<br>
	 * @param close_peer Close the connection to a remote peer.<br>
	 * C type : close_peer_callback*<br>
	 * @param open_channel Open a message channel to a connected peer.<br>
	 * C type : open_channel_callback*<br>
	 * @param close_channel Close a message channel to a connected peer.<br>
	 * C type : close_channel_callback*<br>
	 * @param send_message Send a message to a connected peer over an opened message channel.<br>
	 * C type : send_message_callback*
	 */
	public IDiscordNetworkManager(get_peer_id_callback get_peer_id, flush_callback flush, open_peer_callback open_peer, update_peer_callback update_peer, close_peer_callback close_peer, open_channel_callback open_channel, close_channel_callback close_channel, send_message_callback send_message) {
		super();
		this.get_peer_id = get_peer_id;
		this.flush = flush;
		this.open_peer = open_peer;
		this.update_peer = update_peer;
		this.close_peer = close_peer;
		this.open_channel = open_channel;
		this.close_channel = close_channel;
		this.send_message = send_message;
	}
	public IDiscordNetworkManager(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends IDiscordNetworkManager implements Structure.ByReference {
		
	};
	public static class ByValue extends IDiscordNetworkManager implements Structure.ByValue {
		
	};
}
